Repository equinor/webviz, pull requests merged in 2023-08, with the labels that each got.

#251 Adjustments to slider component
  frontend/src/lib/components/DiscreteSlider/discreteSlider.tsx
  frontend/src/lib/components/DiscreteSlider/index.ts
  frontend/src/lib/components/Slider/slider.tsx
  frontend/src/modules/DistributionPlot/settings.tsx
  frontend/src/modules/MyModule/settings.tsx
Labels: enhancement

#241 Refactored and improved GUI
  frontend/aliases.json
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/assets/webviz.svg
  frontend/src/framework/Workbench.ts
  frontend/src/framework/internal/components/Content/content.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/header.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
  frontend/src/framework/internal/components/Content/private-components/drawer.tsx
  frontend/src/framework/internal/components/Content/private-components/layout.tsx
  frontend/src/framework/internal/components/LoginButton/loginButton.tsx
  frontend/src/framework/internal/components/NavBar/index.ts
  frontend/src/framework/internal/components/NavBar/navBar.tsx
  frontend/src/framework/internal/components/Settings/private-components/drawer.tsx
  frontend/src/framework/internal/components/Settings/private-components/modulesList.tsx
  frontend/src/framework/internal/components/Settings/private-components/setting.tsx
  frontend/src/framework/internal/components/Settings/private-components/syncSettings.tsx
  frontend/src/framework/internal/components/Settings/private-components/templatesList.tsx
  frontend/src/framework/internal/components/Settings/settings.tsx
  frontend/src/framework/internal/components/SettingsContentPanels/index.ts
  frontend/src/framework/internal/components/SettingsContentPanels/settingsContentPanels.tsx
  frontend/src/framework/internal/components/TopNavBar/index.ts
  frontend/src/framework/internal/components/TopNavBar/topNavBar.tsx
  frontend/src/framework/internal/providers/AuthProvider.tsx
  frontend/src/lib/components/Badge/badge.tsx
  frontend/src/lib/components/Badge/index.ts
  frontend/src/lib/components/Button/button.tsx
  frontend/src/lib/components/CircularProgress/circularProgress.tsx
  frontend/src/lib/components/Label/label.tsx
  frontend/src/lib/components/Menu/index.ts
  frontend/src/lib/components/Menu/menu.tsx
  frontend/src/lib/components/MenuItem/index.ts
  frontend/src/lib/components/MenuItem/menuItem.tsx
  frontend/src/lib/components/ResizablePanels/resizablePanels.tsx
  frontend/src/main.css
  frontend/src/modules/SimulationTimeSeriesSensitivity/settings.tsx
Labels: enhancement

#250 Improved crash-view GUI
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/crashView.tsx
Labels: enhancement

#254 Adjust gitignore for `.vscode`
  .gitignore
Labels: enhancement

#253 [BUGFIX] Dev modules were not imported properly when already part of layout (timing issue)
  frontend/src/modules/registerAllModules.ts
Labels: bug

#245 Disabling dialog buttons when there are no changes
  frontend/src/framework/internal/components/SelectEnsemblesDialog/selectEnsemblesDialog.tsx
Labels: enhancement

#257 Moved and adjusted `SmartNodeSelector` and `VectorSelector`
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/components/SmartNodeSelector/index.ts
  frontend/src/lib/components/SmartNodeSelector/private-components/suggestions.tsx
  frontend/src/lib/components/SmartNodeSelector/private-components/tag.tsx
  frontend/src/lib/components/SmartNodeSelector/private-utils/treeData.ts
  frontend/src/lib/components/SmartNodeSelector/private-utils/treeDataNodeTypes.ts
  frontend/src/lib/components/SmartNodeSelector/private-utils/treeNodeSelection.ts
  frontend/src/lib/components/SmartNodeSelector/smartNodeSelector.tsx
  frontend/src/lib/components/VectorSelector/index.ts
  frontend/src/lib/components/VectorSelector/private-assets/images/aquifer.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/block.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/calculated.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/duplicate.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/field.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/group.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/invalid.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/misc.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/network.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/others.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/region-region.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/region.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/segment.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/unknown.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/well-completion.svg
  frontend/src/lib/components/VectorSelector/private-assets/images/well.svg
  frontend/src/lib/components/VectorSelector/private-assets/vectorDefinitions.ts
  frontend/src/lib/components/VectorSelector/private-utils/VectorSelection.ts
  frontend/src/lib/components/VectorSelector/vectorSelector.tsx
Labels: enhancement

#246 Added dialog to enforce login at start up
  frontend/src/App.tsx
  frontend/src/framework/internal/components/LoginDialog/index.ts
  frontend/src/framework/internal/components/LoginDialog/loginDialog.tsx
  frontend/src/lib/components/Dialog/dialog.tsx
Labels: enhancement

#259 Improved Dialog, Slider and RadioGroup components
  frontend/src/lib/components/Dialog/dialog.tsx
  frontend/src/lib/components/RadioGroup/radioGroup.tsx
  frontend/src/lib/components/Slider/slider.tsx
Labels: enhancement

#264 Add glob to devDependencies
  frontend/compress_static.cjs
  frontend/package-lock.json
  frontend/package.json
Labels: bug, enhancement

#261 Implemented hook for validated state
  frontend/src/framework/internal/components/SelectEnsemblesDialog/selectEnsemblesDialog.tsx
  frontend/src/lib/hooks/useValidState.ts
Labels: enhancement

#258 Simplified color palettes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/framework/Module.tsx
  frontend/src/framework/Workbench.ts
  frontend/src/framework/WorkbenchSettings.ts
  frontend/src/framework/internal/PrivateWorkbenchSettings.ts
  frontend/src/framework/internal/components/ColorPaletteSettings/colorPaletteSettings.tsx
  frontend/src/framework/internal/components/ColorPaletteSettings/index.ts
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/viewContent.tsx
  frontend/src/framework/internal/components/Drawer/drawer.tsx
  frontend/src/framework/internal/components/Drawer/index.ts
  frontend/src/framework/internal/components/NavBar/navBar.tsx
  frontend/src/framework/internal/components/Settings/private-components/modulesList.tsx
  frontend/src/framework/internal/components/Settings/private-components/setting.tsx
  frontend/src/framework/internal/components/Settings/private-components/syncSettings.tsx
  frontend/src/framework/internal/components/Settings/private-components/templatesList.tsx
  frontend/src/framework/internal/components/Settings/settings.tsx
  frontend/src/lib/components/ColorGradient/colorGradient.tsx
  frontend/src/lib/components/ColorGradient/index.ts
  frontend/src/lib/components/ColorTile/colorTile.tsx
  frontend/src/lib/components/ColorTile/index.ts
  frontend/src/lib/components/ColorTileGroup/colorTileGroup.tsx
  frontend/src/lib/components/ColorTileGroup/index.ts
  frontend/src/lib/components/Input/input.tsx
  frontend/src/lib/components/Label/label.tsx
  frontend/src/lib/utils/ColorPalette.ts
  frontend/src/lib/utils/ColorScale.ts
  frontend/src/lib/utils/ColorSet.ts
  frontend/src/lib/utils/screenUnitConversions.ts
  frontend/src/modules/DistributionPlot/components/barChart.tsx
  frontend/src/modules/DistributionPlot/components/histogram.tsx
  frontend/src/modules/DistributionPlot/components/scatterPlotWithColorMapping.tsx
  frontend/src/modules/DistributionPlot/view.tsx
  frontend/src/modules/MyModule/loadModule.tsx
  frontend/src/modules/MyModule/settings.tsx
  frontend/src/modules/MyModule/state.ts
  frontend/src/modules/MyModule/view.tsx
Labels: enhancement

#281 Add export of SmartNodeSelectorSelection
  frontend/src/lib/components/SmartNodeSelector/index.ts
Labels: enhancement

#283 Missing check for input type when treating numbers
  frontend/src/lib/components/Input/input.tsx
Labels: bug

#282 Fixed duplicate key in color gradient
  frontend/src/lib/components/ColorGradient/colorGradient.tsx
Labels: bug

#284 Adjustments to dependency cruiser
  frontend/.dependency-cruiser.cjs
  frontend/src/framework/components/ChannelSelect/channelSelect.tsx
  frontend/src/framework/internal/components/ColorPaletteSettings/colorPaletteSettings.tsx
  frontend/src/framework/internal/components/NavBar/navBar.tsx
  frontend/src/framework/internal/components/Settings/settings.tsx
  frontend/src/lib/components/ApiStateWrapper/apiStateWrapper.tsx
  frontend/src/lib/components/Badge/badge.tsx
  frontend/src/lib/components/BaseComponent/baseComponent.tsx
  frontend/src/lib/components/BaseComponent/index.ts
  frontend/src/lib/components/Button/button.tsx
  frontend/src/lib/components/Checkbox/checkbox.tsx
  frontend/src/lib/components/CircularProgress/circularProgress.tsx
  frontend/src/lib/components/CollapsibleGroup/collapsibleGroup.tsx
  frontend/src/lib/components/ColorTile/colorTile.tsx
  frontend/src/lib/components/ColorTileGroup/colorTileGroup.tsx
  frontend/src/lib/components/Dialog/dialog.tsx
  frontend/src/lib/components/Dropdown/dropdown.tsx
  frontend/src/lib/components/IconButton/iconButton.tsx
  frontend/src/lib/components/Input/input.tsx
  frontend/src/lib/components/Label/label.tsx
  frontend/src/lib/components/RadioGroup/radioGroup.tsx
  frontend/src/lib/components/ResizablePanels/resizablePanels.tsx
  frontend/src/lib/components/Select/select.tsx
  frontend/src/lib/components/Slider/slider.tsx
  frontend/src/lib/components/SmartNodeSelector/private-components/suggestions.tsx
  frontend/src/lib/components/SmartNodeSelector/private-components/tag.tsx
  frontend/src/lib/components/SmartNodeSelector/smartNodeSelector.tsx
  frontend/src/lib/components/Switch/switch.tsx
  frontend/src/lib/components/Table/table.tsx
  frontend/src/lib/components/ToggleButton/toggleButton.tsx
  frontend/src/lib/components/VectorSelector/private-utils/VectorSelection.ts
  frontend/src/lib/components/Virtualization/virtualization.tsx
  frontend/src/lib/components/_component-utils/components.tsx
  frontend/src/lib/utils/resolveClassNames.ts
Labels: enhancement

#280 Improved UX for settings drawer and activating modules
  frontend/src/framework/internal/components/ColorPaletteSettings/index.ts
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
  frontend/src/framework/internal/components/NavBar/navBar.tsx
  frontend/src/framework/internal/components/Settings/private-components/colorPaletteSettings.tsx
  frontend/src/framework/internal/components/Settings/private-components/templatesList.tsx
  frontend/src/framework/internal/components/Settings/settings.tsx
Labels: enhancement

#285 Upgraded to `react@18.2.0` and `@mui/base@5.0.0-beta.13`
  frontend/package-lock.json
  frontend/package.json
  frontend/src/framework/internal/components/LoginButton/loginButton.tsx
  frontend/src/lib/components/Input/input.tsx
  frontend/src/lib/components/SmartNodeSelector/private-components/suggestions.tsx
  frontend/src/main.tsx
  frontend/src/modules/MyModule/settings.tsx
Labels: enhancement, epic

#266 Adjusted `ResizablePanels` to new React effect recommendations and fixed events for touch use
  frontend/src/lib/components/ResizablePanels/resizablePanels.tsx
Labels: bug, enhancement

#203 Well Completion Module
  backend/src/backend/primary/main.py
  backend/src/backend/primary/routers/well_completion/router.py
  backend/src/backend/primary/routers/well_completion/schemas.py
  backend/src/services/sumo_access/well_completion_access.py
  backend/src/services/types/well_completion_types.py
  backend/src/services/utils/well_completion_utils.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/ApiService.ts
  frontend/src/api/index.ts
  frontend/src/api/models/Completions.ts
  frontend/src/api/models/WellCompletionData.ts
  frontend/src/api/models/WellCompletionDataSet.ts
  frontend/src/api/models/WellCompletionUnitInfo.ts
  frontend/src/api/models/WellCompletionUnits.ts
  frontend/src/api/models/WellCompletionWell.ts
  frontend/src/api/models/WellCompletionZone.ts
  frontend/src/api/services/WellCompletionService.ts
  frontend/src/modules/WellCompletion/loadModule.tsx
  frontend/src/modules/WellCompletion/queryHooks.tsx
  frontend/src/modules/WellCompletion/registerModule.ts
  frontend/src/modules/WellCompletion/settings.tsx
  frontend/src/modules/WellCompletion/state.ts
  frontend/src/modules/WellCompletion/utils/stringUtils.ts
  frontend/src/modules/WellCompletion/utils/wellCompletionsDataAccessor.ts
  frontend/src/modules/WellCompletion/view.tsx
  frontend/src/modules/registerAllModules.ts
Labels: enhancement

#288 Fixed bug in `ResizablePanels`
  frontend/src/lib/components/ResizablePanels/resizablePanels.tsx
Labels: bug

#289 Moving module instance number control to `Workbench` and clearing layout on unmount in `App`
  frontend/src/App.tsx
  frontend/src/framework/Module.tsx
  frontend/src/framework/Workbench.ts
Labels: bug, enhancement

#291 Added immediate invocation of callback when subscribing to StateStore
  frontend/src/framework/StateStore.ts
Labels: bug

#292 Sensitivity Module - Handle data series with only 0 values
  frontend/src/modules/Sensitivity/sensitivityChart.tsx
Labels: bug
