Repository equinor/webviz, pull requests merged in 2023-09, with the labels that each got.

#290 Persistent ensemble set selection
  frontend/.dependency-cruiser.cjs
  frontend/src/App.tsx
  frontend/src/framework/Workbench.ts
  frontend/src/framework/internal/components/NavBar/navBar.tsx
  frontend/src/main.tsx
Labels: enhancement

#287 Globally synced settings
  frontend/src/framework/Module.tsx
  frontend/src/framework/internal/components/Settings/private-components/syncSettings.tsx
Labels: enhancement

#295 Fix MultiEnsembleSelect component and update usage
  frontend/src/framework/components/MultiEnsembleSelect/multiEnsembleSelect.tsx
  frontend/src/modules/SimulationTimeSeries/settings.tsx
  frontend/src/modules/SimulationTimeSeriesSensitivity/settings.tsx
Labels: bug

#293 `SimulationTimeSeriesMatrix` module
  frontend/src/framework/WorkbenchSettings.ts
  frontend/src/framework/utils/ensembleUiHelpers.ts
  frontend/src/lib/components/ApiStatesWrapper/apiStatesWrapper.tsx
  frontend/src/lib/components/ApiStatesWrapper/index.ts
  frontend/src/lib/utils/vectorSelectorUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/loadModule.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/preview.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/queryHooks.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/registerModule.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/state.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/createVectorTracesUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/fanchartPlotting.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/statisticsPlotting.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/colorUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/ensemblesVectorListHelper.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/subplotBuilder.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/timeSeriesPlotData.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/vectorSpecificationsAndQueriesUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
  frontend/src/modules/registerAllModules.ts
Labels: enhancement

#307 Fix wildcard usage for VectorSelector in SimulationTimeSeriesMatrix
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
Labels: bug

#304 Fixed div by 0 issue and assigning max or mid value in these cases
  frontend/src/lib/utils/ColorScale.ts
Labels: bug

#308 Deactivated wild cards in single node selection mode
  frontend/src/lib/components/SmartNodeSelector/private-utils/treeData.ts
  frontend/src/lib/components/SmartNodeSelector/smartNodeSelector.tsx
  frontend/src/lib/components/VectorSelector/vectorSelector.tsx
Labels: enhancement

#309 Added global error boundary and recovery functionality
  frontend/src/GlobalErrorBoundary.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/viewContent.tsx
  frontend/src/main.tsx
Labels: enhancement

#316 Implemented debug profiler wrapper around every module in dev mode
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/viewContent.tsx
  frontend/src/framework/internal/components/DebugProfiler/debugProfiler.tsx
  frontend/src/framework/internal/components/DebugProfiler/index.ts
  frontend/src/framework/internal/components/Settings/private-components/setting.tsx
Labels: enhancement

#340 Improvements to GUI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/GlobalErrorBoundary.tsx
  frontend/src/framework/Module.tsx
  frontend/src/framework/ModuleRegistry.ts
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/crashView.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/header.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
  frontend/src/framework/internal/components/Drawer/drawer.tsx
  frontend/src/framework/internal/components/LoginButton/loginButton.tsx
  frontend/src/framework/internal/components/LoginDialog/index.ts
  frontend/src/framework/internal/components/LoginDialog/loginDialog.tsx
  frontend/src/framework/internal/components/NavBar/navBar.tsx
  frontend/src/framework/internal/components/SelectEnsemblesDialog/selectEnsemblesDialog.tsx
  frontend/src/framework/internal/components/Settings/private-components/colorPaletteSettings.tsx
  frontend/src/framework/internal/components/Settings/private-components/modulesList.tsx
  frontend/src/framework/internal/components/Settings/private-components/setting.tsx
  frontend/src/framework/internal/components/Settings/private-components/syncSettings.tsx
  frontend/src/framework/internal/components/Settings/private-components/templatesList.tsx
  frontend/src/framework/internal/components/Settings/settings.tsx
  frontend/src/framework/internal/components/StartScreen/index.ts
  frontend/src/framework/internal/components/StartScreen/startScreen.tsx
  frontend/src/lib/components/CollapsibleGroup/collapsibleGroup.tsx
  frontend/src/lib/components/Dialog/dialog.tsx
  frontend/src/lib/components/Dropdown/dropdown.tsx
  frontend/src/lib/components/Label/label.tsx
  frontend/src/lib/components/ListBox/list-box.tsx
  frontend/src/lib/components/SmartNodeSelector/private-components/tag.tsx
  frontend/src/lib/components/SmartNodeSelector/smartNodeSelector.tsx
  frontend/src/lib/components/Table/table.tsx
  frontend/src/main.tsx
  frontend/src/modules/MyModule/registerModule.ts
  frontend/src/modules/Sensitivity/view.tsx
  frontend/src/modules/SimulationTimeSeries/registerModule.ts
Labels: enhancement

#344 Get profile picture and user details from Microsoft Graph API
  backend/src/backend/auth/auth_helper.py
  backend/src/backend/primary/routers/general.py
  backend/src/services/graph_access/graph_access.py
  backend/src/services/utils/authenticated_user.py
  frontend/src/api/models/UserInfo.ts
  frontend/src/api/services/DefaultService.ts
  frontend/src/framework/internal/components/LoginButton/loginButton.tsx
  frontend/src/framework/internal/providers/AuthProvider.tsx
Labels: enhancement

#349 Fixed two bugs in GUI
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/header.tsx
  frontend/src/framework/internal/components/Content/private-components/layout.tsx
Labels: bug

#310 Proposal for handling of missing/removed modules
  frontend/src/framework/Module.tsx
  frontend/src/framework/ModuleRegistry.ts
  frontend/src/framework/internal/ModuleNotFoundPlaceholder.tsx
Labels: enhancement

#318 Fixes to SmartNodeSelector/VectorSelector
  frontend/src/lib/components/SmartNodeSelector/private-components/suggestions.tsx
  frontend/src/lib/components/SmartNodeSelector/private-components/tag.tsx
  frontend/src/lib/components/SmartNodeSelector/private-utils/treeData.ts
  frontend/src/lib/components/SmartNodeSelector/smartNodeSelector.tsx
  frontend/src/lib/components/VectorSelector/vectorSelector.tsx
Labels: bug, enhancement

#320 Add color by parameter for SimulationTimeSeriesMatrix
  frontend/src/framework/Ensemble.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/loadModule.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/state.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/createVectorTracesUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/fanchartPlotting.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/statisticsPlotting.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/ensemblesContinuousParameterColoring.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/ensemblesVectorListHelper.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/subplotBuilder.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
Labels: enhancement
