Repository equinor/webviz, pull requests merged in 2023-11, with the labels that each got.

#451 Add jupyter notebooks to .gitignore
  .gitignore
Labels: enhancement

#456 Upgraded to `TanstackQuery` v5
  frontend/package-lock.json
  frontend/package.json
  frontend/src/framework/internal/EnsembleSetLoader.ts
  frontend/src/framework/internal/components/SelectEnsemblesDialog/private-components/userAvatar.tsx
  frontend/src/framework/internal/components/SelectEnsemblesDialog/selectEnsemblesDialog.tsx
  frontend/src/framework/internal/providers/QueryClientProvider.tsx
  frontend/src/modules/Grid3D/queryHooks.ts
  frontend/src/modules/Grid3DIntersection/queryHooks.ts
  frontend/src/modules/InplaceVolumetrics/queryHooks.tsx
  frontend/src/modules/Pvt/queryHooks.ts
  frontend/src/modules/Rft/queryHooks.ts
  frontend/src/modules/SimulationTimeSeries/queryHooks.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/queryHooks.tsx
  frontend/src/modules/SimulationTimeSeriesSensitivity/queryHooks.tsx
  frontend/src/modules/SubsurfaceMap/queryHooks.tsx
  frontend/src/modules/TimeSeriesParameterDistribution/queryHooks.tsx
  frontend/src/modules/WellCompletions/queryHooks.tsx
  frontend/src/modules/WellCompletions/settings.tsx
  frontend/src/modules/_shared/Surface/queryHooks.ts
Labels: enhancement

#458 Improved loading UX
  frontend/src/App.tsx
  frontend/src/framework/GuiMessageBroker.ts
  frontend/src/framework/Workbench.ts
  frontend/src/framework/WorkbenchSession.ts
  frontend/src/framework/internal/WorkbenchSessionPrivate.ts
  frontend/src/framework/internal/components/NavBar/navBar.tsx
  frontend/src/framework/internal/components/SelectEnsemblesDialog/selectEnsemblesDialog.tsx
  frontend/src/framework/internal/components/StartScreen/index.ts
  frontend/src/framework/internal/components/StartScreen/startScreen.tsx
  frontend/src/lib/components/WebvizSpinner/index.ts
  frontend/src/lib/components/WebvizSpinner/webvizSpinner.css
  frontend/src/lib/components/WebvizSpinner/webvizSpinner.tsx
  frontend/src/main.tsx
Labels: enhancement

#463 Enabled debugging for Python backend
  .gitignore
  .vscode/launch.json
  backend/.vscode/launch.json
  docker-compose.yml
Labels: enhancement

#468 fix: app not initialising when no ensembles selected from before
  frontend/src/App.tsx
Labels: bug

#431 Advanced test setup
  .github/workflows/webviz.yml
  .gitignore
  frontend/aliases.json
  frontend/jest.config.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/tests/README.md
  frontend/tests/ct/_playwright.config.ts
  frontend/tests/ct/checkbox.test.tsx
  frontend/tests/ct/playwright/index.html
  frontend/tests/ct/playwright/index.tsx
  frontend/tests/e2e/_playwright.config.ts
  frontend/tests/e2e/signIn.test.ts
  frontend/tests/unit/EnsembleParameters.test.ts
  frontend/tests/unit/EnsembleSet.test.ts
  frontend/tests/unit/MinMax.test.ts
  frontend/tests/unit/ParameterListFilterUtils.test.ts
  frontend/tests/unit/SimulationTimeSeriesMatrixUtils.test.ts
  frontend/tests/unit/reservoirSimulationStringUtils.test.ts
  frontend/tests/unit/stateStore.test.ts
  frontend/tests/unit/timestampUtils.test.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vitest.config.ts
Labels: enhancement, refactoring

#480 Bug fix: Keeping the newly selected ensembles in dialog when loading from backend
  frontend/src/framework/internal/components/NavBar/navBar.tsx
Labels: bug

#462 Add observations to SimulationTimeSeriesMatrix
  backend/src/services/sumo_access/observation_access.py
  backend/src/services/sumo_access/observation_types.py
  frontend/src/modules/SimulationTimeSeriesMatrix/queryHooks.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/createVectorTracesUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/subplotBuilder.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/vectorSpecificationsAndQueriesUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
Labels: enhancement

#484 Added button for hiding debug/dev tools, made debug info ignore cursor events
  frontend/src/App.tsx
  frontend/src/framework/GuiMessageBroker.ts
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/viewContent.tsx
  frontend/src/framework/internal/components/DebugProfiler/debugProfiler.tsx
  frontend/src/framework/internal/components/Settings/private-components/setting.tsx
  frontend/src/framework/internal/components/ToggleDevToolsButton/index.ts
  frontend/src/framework/internal/components/ToggleDevToolsButton/toggleDevToolsButton.tsx
Labels: enhancement
