Repository equinor/webviz, pull requests merged in 2023-10, with the labels that each got.

#388 Implemented `GuiMessageBroker`
  frontend/src/App.tsx
  frontend/src/framework/GuiMessageBroker.ts
  frontend/src/framework/Workbench.ts
  frontend/src/framework/internal/components/Content/content.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
  frontend/src/framework/internal/components/Content/private-components/layout.tsx
  frontend/src/framework/internal/components/NavBar/navBar.tsx
  frontend/src/framework/internal/components/Settings/private-components/colorPaletteSettings.tsx
  frontend/src/framework/internal/components/Settings/private-components/modulesList.tsx
  frontend/src/framework/internal/components/Settings/private-components/setting.tsx
  frontend/src/framework/internal/components/Settings/private-components/syncSettings.tsx
  frontend/src/framework/internal/components/Settings/private-components/templatesList.tsx
  frontend/src/framework/internal/components/Settings/settings.tsx
  frontend/src/framework/internal/components/SettingsContentPanels/settingsContentPanels.tsx
  frontend/src/framework/internal/hooks/workbenchHooks.ts
Labels: enhancement

#395 Added overlay in order to prevent images from being draggable
  frontend/src/framework/internal/components/Settings/private-components/modulesList.tsx
Labels: bug

#409 Update to fmu-sumo 0.5.4
  backend/poetry.lock
  backend/pyproject.toml
Labels: bug

#367 SimulationTimeSeriesMatrix fixup
  frontend/src/assets/vectorDefinitions.ts
  frontend/src/framework/EnsembleSet.ts
  frontend/src/framework/utils/ensembleUiHelpers.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/createVectorTracesUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/fanchartPlotting.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/PlotlyTraceUtils/statisticsPlotting.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/ensemblesContinuousParameterColoring.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/subplotBuilder.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
  frontend/src/modules/_shared/reservoirSimulationStringUtils.ts
  frontend/src/modules/_shared/reservoirSimulationUnitTerminology.ts
  frontend/tests/unit-tests/EnsembleSet.test.ts
  frontend/tests/unit-tests/reservoirSimulationStringUtils.test.ts
Labels: bug, enhancement

#404 Parameter list filtering
  frontend/src/framework/EnsembleParameters.ts
  frontend/src/framework/components/ParameterListFilter/index.ts
  frontend/src/framework/components/ParameterListFilter/parameterListFilter.tsx
  frontend/src/framework/components/ParameterListFilter/private-assets/check.svg
  frontend/src/framework/components/ParameterListFilter/private-assets/segment.svg
  frontend/src/framework/components/ParameterListFilter/private-utils/smartNodeSelectorUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/tests/unit-tests/ParameterListFilterUtils.test.ts
Labels: enhancement

#418 Bump `@webviz/subsurface-viewer` to `0.3.1`. Fixes performance issues/crash when loading large surfaces
  frontend/package-lock.json
  frontend/package.json
Labels: bug, enhancement

#419 Multiple bug fixes and improvements related to initial settings, templates, and `ChannelSelect`
  frontend/src/framework/InitialSettings.ts
  frontend/src/framework/Workbench.ts
  frontend/src/framework/components/ChannelSelect/channelSelect.tsx
  frontend/src/modules/DistributionPlot/settings.tsx
  frontend/src/modules/TornadoChart/settings.tsx
  frontend/src/templates/oatTimeSeries.ts
Labels: bug

#416 Implemented `StatusController` and `StatusWriter` for setting/updating the status of modules
  frontend/src/framework/ModuleContext.ts
  frontend/src/framework/ModuleInstance.ts
  frontend/src/framework/ModuleInstanceStatusController.ts
  frontend/src/framework/StatusWriter.ts
  frontend/src/framework/internal/ModuleInstanceStatusControllerInternal.ts
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/header.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/viewContent.tsx
  frontend/src/framework/internal/components/DebugProfiler/debugProfiler.tsx
  frontend/src/framework/internal/components/Settings/private-components/setting.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
  frontend/src/modules/_shared/components/ContentMessage/contentMessage.tsx
  frontend/src/modules/_shared/components/ContentMessage/index.ts
  frontend/tailwind.config.cjs
Labels: enhancement

#247 New UX for connecting data channels
  frontend/src/App.tsx
  frontend/src/framework/Broadcaster.ts
  frontend/src/framework/GuiMessageBroker.ts
  frontend/src/framework/Module.tsx
  frontend/src/framework/ModuleContext.ts
  frontend/src/framework/ModuleInstance.ts
  frontend/src/framework/ModuleRegistry.ts
  frontend/src/framework/Workbench.ts
  frontend/src/framework/components/ChannelSelect/channelSelect.tsx
  frontend/src/framework/internal/GlobalCursor.ts
  frontend/src/framework/internal/ModuleNotFoundPlaceholder.tsx
  frontend/src/framework/internal/components/Content/content.tsx
  frontend/src/framework/internal/components/Content/private-components/DataChannelVisualizationLayer/dataChannelVisualizationLayer.tsx
  frontend/src/framework/internal/components/Content/private-components/DataChannelVisualizationLayer/index.ts
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/channelSelector.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/header.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/inputChannelNode.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/inputChannelNodeWrapper.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
  frontend/src/lib/components/Slider/slider.tsx
  frontend/src/lib/hooks/useElementBoundingRect.ts
  frontend/src/modules/DistributionPlot/loadModule.tsx
  frontend/src/modules/DistributionPlot/registerModule.ts
  frontend/src/modules/DistributionPlot/settings.tsx
  frontend/src/modules/DistributionPlot/state.ts
  frontend/src/modules/DistributionPlot/view.tsx
  frontend/src/modules/MyModule/registerModule.ts
  frontend/src/modules/TornadoChart/registerModule.ts
  frontend/src/modules/TornadoChart/settings.tsx
  frontend/src/modules/TornadoChart/state.ts
  frontend/src/modules/TornadoChart/view.tsx
  frontend/src/templates/oatTimeSeries.ts
Labels: enhancement

#423 Fixed wrong class usage in `useSettingsStatusWriter`
  frontend/src/framework/StatusWriter.ts
Labels: bug

#426 Improved icon sizes in `SmartNodeSelector`
  frontend/src/lib/components/SmartNodeSelector/private-components/tag.tsx
  frontend/src/lib/components/SmartNodeSelector/smartNodeSelector.tsx
Labels: bug, enhancement

#425 Add usage of status writer in Map module
  frontend/src/modules/Map/MapSettings.tsx
  frontend/src/modules/Map/MapView.tsx
Labels: enhancement

#424 Improve usage of status writer for settings and view in SimulationTimeSeriesMatrix
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/utils/stringUtils.ts
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
  frontend/tests/unit-tests/SimulationTimeSeriesMatrixUtils.test.ts
Labels: enhancement

#441 Bugfix: Pointer up on module was enough to activate it
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
Labels: bug

#446 Fixed visualization bug in `SmartNodeSelector`
  frontend/src/lib/components/SmartNodeSelector/private-components/tag.tsx
  frontend/src/lib/components/SmartNodeSelector/smartNodeSelector.tsx
Labels: bug

#444 `Select` and `Virtualization` fixes
  frontend/src/lib/components/Select/select.tsx
  frontend/src/lib/components/Virtualization/virtualization.tsx
Labels: bug, enhancement
