Repository equinor/webviz, pull requests merged in 2024-09, with the labels that each got.

#700 Fix multi select initial anchor issue
  frontend/src/lib/components/Select/select.tsx
Labels: bug

#719 remove seismic intersection module
  frontend/src/modules/SeismicIntersection/interfaces.ts
  frontend/src/modules/SeismicIntersection/loadModule.tsx
  frontend/src/modules/SeismicIntersection/queryHooks.tsx
  frontend/src/modules/SeismicIntersection/registerModule.ts
  frontend/src/modules/SeismicIntersection/settings/atoms/baseAtoms.ts
  frontend/src/modules/SeismicIntersection/settings/hooks/queryHooks.tsx
  frontend/src/modules/SeismicIntersection/settings/settings.tsx
  frontend/src/modules/SeismicIntersection/typesAndEnums.ts
  frontend/src/modules/SeismicIntersection/utils/esvIntersectionControllerUtils.ts
  frontend/src/modules/SeismicIntersection/utils/esvIntersectionDataConversion.ts
  frontend/src/modules/SeismicIntersection/utils/esvIntersectionHooks.ts
  frontend/src/modules/SeismicIntersection/utils/esvIntersectionTypes.ts
  frontend/src/modules/SeismicIntersection/utils/queryDataTransforms.ts
  frontend/src/modules/SeismicIntersection/utils/seismicCubeDirectory.ts
  frontend/src/modules/SeismicIntersection/view.tsx
  frontend/src/modules/registerAllModules.ts
Labels: enhancement

#723 Update well-completions-plot version
  frontend/package-lock.json
  frontend/package.json
Labels: bug, enhancement

#726 Bugfix: `Intersection` `Wellpicks` layer re-render issue
  frontend/src/modules/Intersection/settings/components/layerSettings/wellpicksLayer.tsx
  frontend/src/modules/Intersection/utils/layers/BaseLayer.ts
Labels: bug

#685 Implementation of `SortableList` component (+ sub components) and menu utility components
  frontend/src/lib/components/MenuDivider/index.ts
  frontend/src/lib/components/MenuDivider/menuDivider.tsx
  frontend/src/lib/components/MenuHeading/index.ts
  frontend/src/lib/components/MenuHeading/menuHeading.tsx
  frontend/src/lib/components/SortableList/index.ts
  frontend/src/lib/components/SortableList/sortableList.tsx
  frontend/src/lib/components/SortableList/sortableListDropIndicator.tsx
  frontend/src/lib/components/SortableList/sortableListGroup.tsx
  frontend/src/lib/components/SortableList/sortableListItem.tsx
  frontend/src/main.css
  frontend/src/modules/MyModule2/settings.tsx
Labels: enhancement
