Repository equinor/webviz, pull requests merged in 2024-01, with the labels that each got.

#521 Adjust warning message for statusWriter in SimulationTimeSeriesMatrix module
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
Labels: bug, enhancement

#516 Surfaces into seismic intersection
  backend/src/backend/primary/routers/surface/converters.py
  backend/src/backend/primary/routers/surface/router.py
  backend/src/backend/primary/routers/surface/schemas.py
  backend/src/services/sumo_access/surface_access.py
  backend/src/services/sumo_access/surface_types.py
  frontend/src/api/index.ts
  frontend/src/api/models/Body_post_get_surface_intersection.ts
  frontend/src/api/models/SurfaceIntersectionCumulativeLengthPolyline.ts
  frontend/src/api/models/SurfaceIntersectionData.ts
  frontend/src/api/services/SurfaceService.ts
  frontend/src/modules/Map/MapSettings.tsx
  frontend/src/modules/SeismicIntersection/loadModule.tsx
  frontend/src/modules/SeismicIntersection/queryHooks.tsx
  frontend/src/modules/SeismicIntersection/settings.tsx
  frontend/src/modules/SeismicIntersection/state.ts
  frontend/src/modules/SeismicIntersection/types.ts
  frontend/src/modules/SeismicIntersection/utils/esvIntersectionControllerUtils.ts
  frontend/src/modules/SeismicIntersection/utils/esvIntersectionDataConversion.ts
  frontend/src/modules/SeismicIntersection/utils/seismicCubeDirectory.ts
  frontend/src/modules/SeismicIntersection/view.tsx
  frontend/src/modules/SubsurfaceMap/settings.tsx
  frontend/src/modules/_shared/Surface/index.ts
  frontend/src/modules/_shared/Surface/surfaceDirectory.ts
Labels: enhancement

#531 Fixed issue in `DebugProfiler` due to new @types/react version
  frontend/src/framework/internal/components/DebugProfiler/debugProfiler.tsx
Labels: bug

#529 Improvement create vector selector data from vectors
  frontend/src/framework/components/VectorSelector/vectorSelector.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/tests/unit/VectorSelectorUtils.test.ts
Labels: enhancement

#533 Fixed issues with z-index of marks and overflow in `Slider` component
  frontend/src/lib/components/Slider/slider.tsx
Labels: bug
