Repository equinor/webviz, pull requests merged in 2024-04, with the labels that each got.

#583 Fixed resizable panel issues and added component test
  frontend/src/lib/components/ResizablePanels/resizablePanels.tsx
  frontend/tests/ct/checkbox.test.tsx
  frontend/tests/ct/resizablePanels.test.tsx
  frontend/tests/ct/select.test.tsx
  frontend/tests/utils/compare.ts
Labels: bug, enhancement

#597 Adjust gitignore to ignore virtual env starting with `.venv`
  .gitignore
Labels: enhancement

#582 Refactoring of PVT module based on atoms and new interface
  frontend/src/framework/GlobalAtoms.ts
  frontend/src/framework/StatusWriter.ts
  frontend/src/framework/UniDirectionalSettingsToViewInterface.ts
  frontend/src/framework/components/EnsembleDropdown/ensembleDropdown.tsx
  frontend/src/framework/components/EnsembleDropdown/index.ts
  frontend/src/framework/components/EnsembleSelect/ensembleSelect.tsx
  frontend/src/framework/components/EnsembleSelect/index.ts
  frontend/src/framework/components/MultiEnsembleSelect/index.ts
  frontend/src/framework/components/SingleEnsembleSelect/index.ts
  frontend/src/framework/internal/WorkbenchSessionPrivate.ts
  frontend/src/framework/internal/components/LeftSettingsPanel/private-components/modulesList.tsx
  frontend/src/lib/components/PendingWrapper/pendingWrapper.tsx
  frontend/src/lib/components/RadioGroup/index.ts
  frontend/src/lib/components/RadioGroup/radioGroup.tsx
  frontend/src/modules/DistributionPlot/view.tsx
  frontend/src/modules/InplaceVolumetrics/settings.tsx
  frontend/src/modules/Map/MapSettings.tsx
  frontend/src/modules/ParameterDistributionMatrix/settings.tsx
  frontend/src/modules/Pvt/loadModule.tsx
  frontend/src/modules/Pvt/plotlyPvtScatter.tsx
  frontend/src/modules/Pvt/pvtPlotDataAccessor.ts
  frontend/src/modules/Pvt/pvtQueryDataAccessor.ts
  frontend/src/modules/Pvt/queryHooks.ts
  frontend/src/modules/Pvt/registerModule.tsx
  frontend/src/modules/Pvt/settings.tsx
  frontend/src/modules/Pvt/settings/atoms/baseAtoms.ts
  frontend/src/modules/Pvt/settings/atoms/derivedAtoms.ts
  frontend/src/modules/Pvt/settings/atoms/queryAtoms.ts
  frontend/src/modules/Pvt/settings/components/DependentVariableSelector/dependentVariableSelector.tsx
  frontend/src/modules/Pvt/settings/components/DependentVariableSelector/index.ts
  frontend/src/modules/Pvt/settings/settings.tsx
  frontend/src/modules/Pvt/state.ts
  frontend/src/modules/Pvt/typesAndEnums.ts
  frontend/src/modules/Pvt/utils/PvtDataAccessor.ts
  frontend/src/modules/Pvt/utils/PvtPlotBuilder.ts
  frontend/src/modules/Pvt/utils/realizationsIntersection.ts
  frontend/src/modules/Pvt/view.tsx
  frontend/src/modules/Rft/settings.tsx
  frontend/src/modules/SeismicIntersection/settings.tsx
  frontend/src/modules/SimulationTimeSeries/settings.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/settings.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
  frontend/src/modules/SimulationTimeSeriesSensitivity/settings.tsx
  frontend/src/modules/StructuralUncertaintyIntersection/settings.tsx
  frontend/src/modules/SubsurfaceMap/settings.tsx
  frontend/src/modules/TimeSeriesParameterDistribution/settings.tsx
  frontend/src/modules/WellCompletions/settings.tsx
  frontend/src/modules/_shared/Figure.tsx
  frontend/src/modules/_shared/ensembleNameUtils.ts
Labels: enhancement, refactoring

#609 Refactor parameter matrix module
  frontend/src/modules/ParameterDistributionMatrix/components/ParameterDistributionPlot/index.ts
  frontend/src/modules/ParameterDistributionMatrix/loadModule.tsx
  frontend/src/modules/ParameterDistributionMatrix/registerModule.ts
  frontend/src/modules/ParameterDistributionMatrix/registerModule.tsx
  frontend/src/modules/ParameterDistributionMatrix/settings.tsx
  frontend/src/modules/ParameterDistributionMatrix/settings/atoms/baseAtoms.ts
  frontend/src/modules/ParameterDistributionMatrix/settings/atoms/derivedAtoms.ts
  frontend/src/modules/ParameterDistributionMatrix/settings/settings.tsx
  frontend/src/modules/ParameterDistributionMatrix/settingsToViewInterface.ts
  frontend/src/modules/ParameterDistributionMatrix/state.ts
  frontend/src/modules/ParameterDistributionMatrix/typesAndEnums.ts
  frontend/src/modules/ParameterDistributionMatrix/view.tsx
  frontend/src/modules/ParameterDistributionMatrix/view/components/ParameterDistributionPlot.tsx
  frontend/src/modules/ParameterDistributionMatrix/view/view.tsx
Labels: enhancement

#611 Parameter distribution Matrix show underlying data
  frontend/src/modules/ParameterDistributionMatrix/settings/settings.tsx
  frontend/src/modules/ParameterDistributionMatrix/settingsToViewInterface.ts
  frontend/src/modules/ParameterDistributionMatrix/typesAndEnums.ts
  frontend/src/modules/ParameterDistributionMatrix/view/components/ParameterDistributionPlot.tsx
  frontend/src/modules/ParameterDistributionMatrix/view/view.tsx
  frontend/src/modules/_shared/statistics.ts
Labels: enhancement

#616 Fixed bug where scrolling is not detected
  frontend/src/lib/hooks/useElementBoundingRect.ts
Labels: bug

#581 Refactored `SimulationTimeSeries` to be like `SimulationTimeSeriesMatrix` but with `Jotai` atoms
  frontend/src/framework/Module.tsx
  frontend/src/framework/ModuleContext.ts
  frontend/src/framework/ModuleInstance.ts
  frontend/src/framework/ModuleRegistry.ts
  frontend/src/framework/StatusWriter.ts
  frontend/src/framework/UniDirectionalSettingsToViewInterface.ts
  frontend/src/framework/Workbench.ts
  frontend/src/framework/internal/ModuleNotFoundPlaceholder.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/channelReceiverNodesWrapper.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/header.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/viewContent.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
  frontend/src/framework/internal/components/ErrorBoundary/errorBoundary.tsx
  frontend/src/framework/internal/components/LeftSettingsPanel/private-components/moduleSettings.tsx
  frontend/src/framework/internal/hooks/moduleHooks.ts
  frontend/src/framework/internal/hooks/workbenchHooks.ts
  frontend/src/modules/SimulationTimeSeries/channelDefs.ts
  frontend/src/modules/SimulationTimeSeries/dataGenerators.ts
  frontend/src/modules/SimulationTimeSeries/loadModule.tsx
  frontend/src/modules/SimulationTimeSeries/preview.svg
  frontend/src/modules/SimulationTimeSeries/queryHooks.tsx
  frontend/src/modules/SimulationTimeSeries/registerModule.ts
  frontend/src/modules/SimulationTimeSeries/settings.tsx
  frontend/src/modules/SimulationTimeSeries/settings/atoms/atomDefinitions.ts
  frontend/src/modules/SimulationTimeSeries/settings/atoms/baseAtoms.ts
  frontend/src/modules/SimulationTimeSeries/settings/atoms/derivedAtoms.ts
  frontend/src/modules/SimulationTimeSeries/settings/atoms/queryAtoms.ts
  frontend/src/modules/SimulationTimeSeries/settings/hooks/useMakeSettingsStatusWriterMessages.ts
  frontend/src/modules/SimulationTimeSeries/settings/settings.tsx
  frontend/src/modules/SimulationTimeSeries/settingsToViewInterface.ts
  frontend/src/modules/SimulationTimeSeries/state.ts
  frontend/src/modules/SimulationTimeSeries/typesAndEnums.ts
  frontend/src/modules/SimulationTimeSeries/utils/ensemblesVectorListHelper.ts
  frontend/src/modules/SimulationTimeSeries/utils/stringUtils.ts
  frontend/src/modules/SimulationTimeSeries/view.tsx
  frontend/src/modules/SimulationTimeSeries/view/atoms/atomDefinitions.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/useMakeEnsembleDisplayNameFunc.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/useMakeViewStatusWriterMessages.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/usePublishToDataChannels.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/useSubplotBuilder.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/PlotlyTraceUtils/createVectorTracesUtils.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/PlotlyTraceUtils/fanchartPlotting.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/PlotlyTraceUtils/statisticsPlotting.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/colorUtils.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/ensemblesContinuousParameterColoring.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/subplotBuilder.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/timeSeriesPlotData.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/vectorSpecificationsAndQueriesUtils.ts
  frontend/src/modules/SimulationTimeSeries/view/view.tsx
  frontend/src/modules/SimulationTimeSeriesMatrix/view.tsx
  frontend/src/modules/SubsurfaceMap/components/SyncedSubsurfaceViewer/syncedSubsurfaceViewer.tsx
Labels: enhancement, refactoring
