Repository equinor/webviz, pull requests merged in 2024-10, with the labels that each got.

#744 Adjust gap for RadioGroup component
  frontend/src/lib/components/RadioGroup/radioGroup.tsx
Labels: enhancement

#748 Implementation of `DenseIconButton`
  frontend/src/lib/components/DenseIconButton/denseIconButton.tsx
  frontend/src/lib/components/DenseIconButton/index.ts
Labels: enhancement

#750 Adjust color prop for Button-component
  frontend/src/lib/components/Button/button.tsx
Labels: bug, enhancement

#752 `Moved to Amsterdam` notification
  frontend/src/main.tsx
  frontend/src/tempMoved/TempMovedToAmsterdamNotifier.tsx
  frontend/src/tempMoved/WebvizSpinner/index.ts
  frontend/src/tempMoved/WebvizSpinner/webvizSpinnerAmsterdam.css
  frontend/src/tempMoved/WebvizSpinner/webvizSpinnerAmsterdam.tsx
Labels: enhancement

#759 Fix missing key in `React.Fragment` in `LogList` component
  frontend/src/framework/internal/components/RightSettingsPanel/private-components/ModuleInstanceLog/moduleInstanceLog.tsx
Labels: bug

#755 Improve UX for Color realization by parameter in SimulationTimeSeries
  frontend/src/framework/components/ParameterListFilter/parameterListFilter.tsx
  frontend/src/lib/components/IconButton/iconButton.tsx
  frontend/src/modules/SimulationTimeSeries/settings/settings.tsx
Labels: enhancement

#772 771 fix categorization of discrete parameters
  backend_py/primary/primary/main.py
  backend_py/primary/primary/routers/correlations/__init__.py
  backend_py/primary/primary/routers/correlations/router.py
  backend_py/primary/primary/routers/parameters/router.py
  backend_py/primary/primary/routers/parameters/schemas.py
  backend_py/primary/primary/services/parameter_correlations.py
  backend_py/primary/primary/services/sumo_access/parameter_access.py
  backend_py/primary/primary/services/sumo_access/parameter_types.py
  frontend/src/api/models/EnsembleParameter.ts
  frontend/src/api/models/EnsembleParameterDescription.ts
  frontend/src/framework/internal/EnsembleSetLoader.ts
Labels: bug, enhancement

#773 769 add disable for dense icon button
  frontend/src/lib/components/DenseIconButton/denseIconButton.tsx
Labels: enhancement
