Repository equinor/webviz, pull requests merged in 2024-12, with the labels that each got.

#794 Implement Well-log viewer module MVP
  backend_py/primary/primary/routers/well/converters.py
  backend_py/primary/primary/routers/well/router.py
  backend_py/primary/primary/routers/well/schemas.py
  backend_py/primary/primary/services/ssdl_access/types.py
  backend_py/primary/primary/services/ssdl_access/well_access.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/models/WellboreLogCurveData.ts
  frontend/src/api/models/WellboreLogCurveHeader.ts
  frontend/src/lib/components/Dropdown/dropdown.tsx
  frontend/src/lib/components/Virtualization/virtualization.tsx
  frontend/src/lib/utils/arrays.ts
  frontend/src/modules/WellLogViewer/interfaces.ts
  frontend/src/modules/WellLogViewer/loadModule.tsx
  frontend/src/modules/WellLogViewer/preview.svg
  frontend/src/modules/WellLogViewer/preview.tsx
  frontend/src/modules/WellLogViewer/registerModule.ts
  frontend/src/modules/WellLogViewer/settings/atoms/baseAtoms.ts
  frontend/src/modules/WellLogViewer/settings/atoms/derivedAtoms.ts
  frontend/src/modules/WellLogViewer/settings/atoms/persistedAtoms.ts
  frontend/src/modules/WellLogViewer/settings/atoms/queryAtoms.ts
  frontend/src/modules/WellLogViewer/settings/components/AddItemButton.tsx
  frontend/src/modules/WellLogViewer/settings/components/TemplateTrackSettings/index.ts
  frontend/src/modules/WellLogViewer/settings/components/TemplateTrackSettings/private-components/SortablePlotList.tsx
  frontend/src/modules/WellLogViewer/settings/components/TemplateTrackSettings/private-components/SortableTrackItem.tsx
  frontend/src/modules/WellLogViewer/settings/components/TemplateTrackSettings/private-components/TrackSettings.tsx
  frontend/src/modules/WellLogViewer/settings/components/TemplateTrackSettings/private-components/plotTypeOptions.tsx
  frontend/src/modules/WellLogViewer/settings/components/TemplateTrackSettings/templateTrackSettings.tsx
  frontend/src/modules/WellLogViewer/settings/components/ViewerSettings.tsx
  frontend/src/modules/WellLogViewer/settings/components/WellpickSelect.tsx
  frontend/src/modules/WellLogViewer/settings/settings.tsx
  frontend/src/modules/WellLogViewer/types.ts
  frontend/src/modules/WellLogViewer/utils/atoms.ts
  frontend/src/modules/WellLogViewer/utils/logViewerColors.ts
  frontend/src/modules/WellLogViewer/utils/logViewerTemplate.ts
  frontend/src/modules/WellLogViewer/utils/queryDataTransform.ts
  frontend/src/modules/WellLogViewer/utils/settingsImport.ts
  frontend/src/modules/WellLogViewer/view/atoms/baseAtoms.ts
  frontend/src/modules/WellLogViewer/view/atoms/derivedAtoms.ts
  frontend/src/modules/WellLogViewer/view/atoms/interfaceEffects.ts
  frontend/src/modules/WellLogViewer/view/atoms/queryAtoms.ts
  frontend/src/modules/WellLogViewer/view/components/ReadoutWrapper.tsx
  frontend/src/modules/WellLogViewer/view/components/SubsurfaceLogViewerWrapper.tsx
  frontend/src/modules/WellLogViewer/view/queries/shared.ts
  frontend/src/modules/WellLogViewer/view/queries/wellLogQueries.ts
  frontend/src/modules/WellLogViewer/view/view.tsx
  frontend/src/modules/_shared/hooks/usePropagateApiErrorToStatusWriter.ts
  frontend/src/modules/registerAllModules.ts
  frontend/tests/unit/WellLogViewer/logViewerTemplate.test.ts
  frontend/tests/unit/WellLogViewer/queryDataTransform.test.ts
Labels: enhancement

#809 Multiple enhancements, adjustments, and bug fixes to frontend code
  frontend/src/framework/ModuleDataTags.ts
  frontend/src/framework/WorkbenchSession.ts
  frontend/src/framework/components/EnsembleDropdown/ensembleDropdown.tsx
  frontend/src/framework/components/EnsembleSelect/ensembleSelect.tsx
  frontend/src/framework/internal/components/LeftSettingsPanel/private-components/modulesList.tsx
  frontend/src/framework/utils/colorPalettes.ts
  frontend/src/lib/components/Input/input.tsx
  frontend/src/lib/components/MenuButton/index.ts
  frontend/src/lib/components/MenuButton/menuButton.tsx
  frontend/src/lib/components/MenuHeading/menuHeading.tsx
  frontend/src/lib/components/SortableList/index.ts
  frontend/src/lib/components/SortableList/sortableListGroup.tsx
  frontend/src/lib/components/SortableList/sortableListItem.tsx
  frontend/src/lib/utils/ColorPalette.ts
  frontend/src/lib/utils/ColorScale.ts
  frontend/src/modules/3DViewer/settings/components/wellboreSelector.tsx
  frontend/src/modules/3DViewer/settings/settings.tsx
  frontend/src/modules/3DViewer/view/components/SubsurfaceViewerWrapper.tsx
  frontend/src/modules/FlowNetwork/settings/settings.tsx
  frontend/src/modules/Intersection/settings/components/layerSettings/gridLayer.tsx
  frontend/src/modules/Intersection/settings/components/layerSettings/seismicLayer.tsx
  frontend/src/modules/Intersection/settings/components/layerSettings/surfaceLayer.tsx
  frontend/src/modules/Intersection/settings/components/layerSettings/surfacesUncertaintyLayer.tsx
  frontend/src/modules/Intersection/settings/components/layerSettings/wellpicksLayer.tsx
  frontend/src/modules/Map/settings/settings.tsx
  frontend/src/modules/ParameterDistributionMatrix/settings/settings.tsx
  frontend/src/modules/Pvt/settings/settings.tsx
  frontend/src/modules/Rft/settings.tsx
  frontend/src/modules/SimulationTimeSeries/settings/settings.tsx
  frontend/src/modules/SimulationTimeSeriesSensitivity/settings/settings.tsx
  frontend/src/modules/SubsurfaceMap/settings/settings.tsx
  frontend/src/modules/Vfp/settings/settings.tsx
  frontend/src/modules/WellCompletions/settings/settings.tsx
  frontend/src/modules/_shared/components/ColorLegendsContainer/colorLegendsContainer.tsx
  frontend/src/modules/_shared/components/ColorScaleSelector/colorScaleSelector.tsx
  frontend/src/modules/_shared/components/InplaceVolumetricsFilterComponent/inplaceVolumetricsFilterComponent.tsx
  frontend/src/modules/_shared/components/ReadoutBox.tsx
  frontend/src/modules/_shared/components/SubsurfaceViewerWithCameraState/index.ts
  frontend/src/modules/_shared/components/SubsurfaceViewerWithCameraState/subsurfaceViewerWithCameraState.tsx
  package-lock.json
Labels: enhancement

#825 Refactoring - Added utility to simplify drogon identifier comparisons
  backend_py/primary/primary/routers/polygons/router.py
  backend_py/primary/primary/routers/surface/router.py
  backend_py/primary/primary/routers/well/router.py
  backend_py/primary/primary/utils/drogon.py
Labels: refactoring, small issue

#824 Refactor - Removed unused duplicated strat unit schema
  backend_py/primary/primary/routers/surface/schemas.py
  backend_py/primary/primary/routers/well/converters.py
  backend_py/primary/primary/routers/well/schemas.py
  frontend/src/api/models/StratigraphicUnit.ts
Labels: refactoring, small issue

#829 fix: `LayerManagerComponentWrapper` not updating when items in `LayerManager` are changing
  frontend/src/modules/2DViewer/registerModule.ts
  frontend/src/modules/2DViewer/settings/components/layerManagerComponentWrapper.tsx
  frontend/src/modules/2DViewer/settings/settings.tsx
Labels: bug
