Repository equinor/webviz, pull requests merged in 2024-07, with the labels that each got.

#663 Improve errors frontend
  backend_py/primary/primary/services/sumo_access/queries/grid3d.py
  backend_py/primary/primary/services/sumo_access/well_completions_access.py
  frontend/.dependency-cruiser.cjs
  frontend/src/App.tsx
  frontend/src/framework/GuiMessageBroker.ts
  frontend/src/framework/ModuleInstanceStatusController.ts
  frontend/src/framework/StatusWriter.ts
  frontend/src/framework/internal/ModuleInstanceStatusControllerInternal.ts
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/private-components/header.tsx
  frontend/src/framework/internal/components/Content/private-components/ViewWrapper/viewWrapper.tsx
  frontend/src/framework/internal/components/Drawer/drawer.tsx
  frontend/src/framework/internal/components/LeftSettingsPanel/leftSettingsPanel.tsx
  frontend/src/framework/internal/components/LeftSettingsPanel/private-components/colorPaletteSettings.tsx
  frontend/src/framework/internal/components/LeftSettingsPanel/private-components/modulesList.tsx
  frontend/src/framework/internal/components/LeftSettingsPanel/private-components/syncSettings.tsx
  frontend/src/framework/internal/components/LeftSettingsPanel/private-components/templatesList.tsx
  frontend/src/framework/internal/components/NavBar/leftNavBar.tsx
  frontend/src/framework/internal/components/NavBar/rightNavBar.tsx
  frontend/src/framework/internal/components/RightSettingsPanel/private-components/ModuleInstanceLog/index.ts
  frontend/src/framework/internal/components/RightSettingsPanel/private-components/ModuleInstanceLog/moduleInstanceLog.tsx
  frontend/src/framework/internal/components/RightSettingsPanel/private-components/RealizationFilterSettings/index.ts
  frontend/src/framework/internal/components/RightSettingsPanel/private-components/RealizationFilterSettings/realizationFilterSettings.tsx
  frontend/src/framework/internal/components/RightSettingsPanel/private-components/RealizationFilterSettings/utils/dataTypeConversion.ts
  frontend/src/framework/internal/components/RightSettingsPanel/rightSettingsPanel.tsx
  frontend/src/framework/internal/components/SettingsContentPanels/settingsContentPanels.tsx
  frontend/src/framework/utils/ApiErrorHelper.ts
  frontend/src/modules/3DViewer/settings/settings.tsx
  frontend/src/modules/3DViewer/view/view.tsx
  frontend/src/modules/FlowNetwork/settings/settings.tsx
  frontend/src/modules/Intersection/settings/components/layers.tsx
  frontend/src/modules/Intersection/settings/settings.tsx
  frontend/src/modules/Intersection/utils/layers/BaseLayer.ts
  frontend/src/modules/Intersection/view/view.tsx
  frontend/src/modules/Map/MapSettings.tsx
  frontend/src/modules/Map/MapView.tsx
  frontend/src/modules/Pvt/settings/atoms/queryAtoms.ts
  frontend/src/modules/Pvt/typesAndEnums.ts
  frontend/src/modules/Pvt/view.tsx
  frontend/src/modules/SeismicIntersection/settings.tsx
  frontend/src/modules/SeismicIntersection/view.tsx
  frontend/src/modules/StructuralUncertaintyIntersection/settings.tsx
  frontend/src/modules/StructuralUncertaintyIntersection/view.tsx
  frontend/src/modules/WellCompletions/settings.tsx
  frontend/src/modules/_shared/hooks/usePropagateApiErrorToStatusWriter.ts
Labels: enhancement

#666 Fixed dangling modifiers and focus issues in `Select` component
  frontend/src/lib/components/Select/select.tsx
Labels: bug

#670 Removed `baseStates` / `derivedStates` logic in module interface
  frontend/src/framework/Module.tsx
  frontend/src/framework/ModuleContext.ts
  frontend/src/framework/ModuleInstance.ts
  frontend/src/framework/ModuleRegistry.ts
  frontend/src/framework/UniDirectionalModuleComponentsInterface.ts
  frontend/src/framework/UniDirectionalSettingsToViewInterface.ts
  frontend/src/framework/internal/ModuleNotFoundPlaceholder.tsx
  frontend/src/modules/3DViewer/settings/atoms/baseAtoms.ts
  frontend/src/modules/3DViewer/settings/settings.tsx
  frontend/src/modules/3DViewer/settingsToViewInterface.ts
  frontend/src/modules/FlowNetwork/settingsToViewInterface.ts
  frontend/src/modules/Intersection/settings/atoms/baseAtoms.ts
  frontend/src/modules/Intersection/settings/settings.tsx
  frontend/src/modules/Intersection/settingsToViewInterface.ts
  frontend/src/modules/Intersection/view/atoms/atomDefinitions.ts
  frontend/src/modules/MyModule2/loadModule.tsx
  frontend/src/modules/MyModule2/registerModule.ts
  frontend/src/modules/MyModule2/settings.tsx
  frontend/src/modules/MyModule2/state.ts
  frontend/src/modules/MyModule2/view.tsx
  frontend/src/modules/ParameterDistributionMatrix/settings/atoms/baseAtoms.ts
  frontend/src/modules/ParameterDistributionMatrix/settings/settings.tsx
  frontend/src/modules/ParameterDistributionMatrix/settingsToViewInterface.ts
  frontend/src/modules/Pvt/loadModule.tsx
  frontend/src/modules/Pvt/registerModule.tsx
  frontend/src/modules/Pvt/settings/atoms/baseAtoms.ts
  frontend/src/modules/Pvt/settings/settings.tsx
  frontend/src/modules/Pvt/settingsToViewInterface.ts
  frontend/src/modules/Pvt/state.ts
  frontend/src/modules/Pvt/view.tsx
  frontend/src/modules/SimulationTimeSeries/loadModule.tsx
  frontend/src/modules/SimulationTimeSeries/registerModule.ts
  frontend/src/modules/SimulationTimeSeries/settings/settings.tsx
  frontend/src/modules/SimulationTimeSeries/settingsToViewInterface.ts
  frontend/src/modules/SimulationTimeSeries/view/atoms/atomDefinitions.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/useMakeEnsembleDisplayNameFunc.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/useMakeViewStatusWriterMessages.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/usePublishToDataChannels.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/useSubplotBuilder.ts
  frontend/src/modules/SimulationTimeSeries/view/view.tsx
Labels: refactoring

#673 Improve ensemble color pre-selection
  frontend/src/framework/internal/components/SelectEnsemblesDialog/selectEnsemblesDialog.tsx
Labels: enhancement

#676 Fix global filterSet atom not updating issue
  frontend/src/framework/GlobalAtoms.ts
  frontend/src/framework/internal/WorkbenchSessionPrivate.ts
  frontend/src/modules/Intersection/settings/atoms/derivedAtoms.ts
Labels: bug

#675 Make usage of edge/node labels in dropdowns in settings
  backend_py/primary/primary/routers/group_tree/schemas.py
  backend_py/primary/primary/services/group_tree_assembler/group_tree_assembler.py
  frontend/src/modules/FlowNetwork/settings/atoms/derivedAtoms.ts
  frontend/src/modules/FlowNetwork/settings/settings.tsx
Labels: enhancement
