Repository equinor/webviz, pull requests merged in 2025-05, with the labels that each got.

#959 Add fieldId to user created polyline
  frontend/src/framework/userCreatedItems/IntersectionPolylines.ts
  frontend/src/modules/3DViewer/view/components/SubsurfaceViewerWrapper.tsx
  frontend/src/modules/3DViewer/view/view.tsx
Labels: enhancement

#971 fix: WebGL context issues
  frontend/src/modules/_shared/components/EsvIntersection/esvIntersection.tsx
Labels: bug

#977 fix: insufficient key in template previews
  frontend/src/framework/internal/components/LeftSettingsPanel/private-components/templatesList.tsx
Labels: bug

#974 Replace incorrect parallel for-loops with async for-loops
  backend_py/primary/primary/services/sumo_access/grid3d_access.py
  backend_py/primary/primary/services/sumo_access/polygons_access.py
  backend_py/primary/primary/services/sumo_access/seismic_access.py
Labels: bug

#910 Move and deprecate endpoints for wellbore and stratigraphic units
  backend_py/primary/primary/routers/surface/converters.py
  backend_py/primary/primary/routers/surface/router.py
  backend_py/primary/primary/routers/surface/schemas.py
  backend_py/primary/primary/routers/well/converters.py
  backend_py/primary/primary/routers/well/router.py
  backend_py/primary/primary/routers/well/schemas.py
  frontend/src/api/autogen/@tanstack/react-query.gen.ts
  frontend/src/api/autogen/sdk.gen.ts
  frontend/src/api/autogen/types.gen.ts
  frontend/src/modules/Intersection/utils/layers/WellpicksLayer.ts
  frontend/src/modules/WellLogViewer/settings/atoms/queryAtoms.ts
Labels: enhancement

#949 [DPF]: Several improvements to dependency tree, data fetching, immutability, destruction handling, shared settings
  frontend/src/framework/components/ColorScaleSelector/colorScaleSelector.tsx
  frontend/src/framework/userCreatedItems/IntersectionPolylines.ts
  frontend/src/lib/components/SortableList/sortableList.tsx
  frontend/src/modules/2DViewer/DataProviderFramework/customDataProviderImplementations/RealizationGridProvider.ts
  frontend/src/modules/2DViewer/DataProviderFramework/customDataProviderImplementations/StatisticalSurfaceProvider.ts
  frontend/src/modules/2DViewer/DataProviderFramework/visualization/makeRealizationGridLayer.ts
  frontend/src/modules/2DViewer/DataProviderFramework/visualization/makeRealizationPolygonsLayer.ts
  frontend/src/modules/2DViewer/settings/settings.tsx
  frontend/src/modules/2DViewer/view/components/LayersWrapper.tsx
  frontend/src/modules/3DViewer/settings/settings.tsx
  frontend/src/modules/3DViewer/view/components/PolylineEditingPanel.tsx
  frontend/src/modules/3DViewer/view/components/SubsurfaceViewerWrapper.tsx
  frontend/src/modules/3DViewer/view/utils/layers.ts
  frontend/src/modules/Intersection/settings/settings.tsx
  frontend/src/modules/_shared/DataProviderFramework/dataProviders/implementations/IntersectionRealizationGridProvider.ts
  frontend/src/modules/_shared/DataProviderFramework/delegates/GroupDelegate.ts
  frontend/src/modules/_shared/DataProviderFramework/delegates/SettingsContextDelegate.ts
  frontend/src/modules/_shared/DataProviderFramework/delegates/SharedSettingsDelegate.ts
  frontend/src/modules/_shared/DataProviderFramework/delegates/_utils/Dependency.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/DataProvider/DataProvider.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/DataProvider/DataProviderComponent.tsx
  frontend/src/modules/_shared/DataProviderFramework/framework/DataProviderManager/DataProviderManager.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/DeltaSurface/DeltaSurface.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/ExternalSettingController/ExternalSettingController.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/Group/Group.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/Group/GroupComponent.tsx
  frontend/src/modules/_shared/DataProviderFramework/framework/SettingManager/SettingManager.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/SettingManager/SettingManagerComponent.tsx
  frontend/src/modules/_shared/DataProviderFramework/framework/SettingsGroup/SettingsGroup.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/SharedSetting/SharedSetting.ts
  frontend/src/modules/_shared/DataProviderFramework/framework/SharedSetting/SharedSettingComponent.tsx
  frontend/src/modules/_shared/DataProviderFramework/framework/utilityComponents/RemoveItemButton.tsx
  frontend/src/modules/_shared/DataProviderFramework/interfacesAndTypes/customDataProviderImplementation.ts
  frontend/src/modules/_shared/DataProviderFramework/interfacesAndTypes/customGroupImplementation.ts
  frontend/src/modules/_shared/DataProviderFramework/interfacesAndTypes/customSettingsHandler.ts
  frontend/src/modules/_shared/DataProviderFramework/interfacesAndTypes/entities.ts
  frontend/src/modules/_shared/DataProviderFramework/settings/settingsDefinitions.ts
  frontend/src/modules/_shared/DataProviderFramework/visualization/VisualizationAssembler.ts
  frontend/src/modules/_shared/DataProviderFramework/visualization/deckgl/makeDrilledWellTrajectoriesLayer.ts
  frontend/src/modules/_shared/DataProviderFramework/visualization/utils/colors.ts
  frontend/src/modules/_shared/components/ColorLegendsContainer/colorLegendsContainer.tsx
Labels: bug, enhancement

#997 Replace Webviz logo with FMU logo
  frontend/src/App.tsx
  frontend/src/assets/fmu.svg
  frontend/src/assets/fmuAnimated.svg
  frontend/src/framework/internal/components/LoadingOverlay/loadingOverlay.tsx
  frontend/src/framework/internal/components/NavBar/leftNavBar.tsx
  frontend/src/lib/components/WebvizSpinner/index.ts
  frontend/src/lib/components/WebvizSpinner/webvizSpinner.css
  frontend/src/lib/components/WebvizSpinner/webvizSpinner.tsx
Labels: enhancement
