Repository equinor/webviz, pull requests merged in 2025-01, with the labels that each got.

#838 Pin poetry to v `1.8.5` and fix deprecated poetry workflow command
  .github/workflows/webviz.yml
Labels: bug

#856 Removed files related to movement notification
  frontend/src/main.tsx
  frontend/src/tempMoved/TempMovedToAmsterdamNotifier.tsx
  frontend/src/tempMoved/WebvizSpinner/index.ts
  frontend/src/tempMoved/WebvizSpinner/webvizSpinnerAmsterdam.css
  frontend/src/tempMoved/WebvizSpinner/webvizSpinnerAmsterdam.tsx
Labels: enhancement

#848 Add subplot grid layout for SimulationTimeSeries
  frontend/src/modules/DistributionPlot/view.tsx
  frontend/src/modules/Pvt/utils/PvtPlotBuilder.ts
  frontend/src/modules/SimulationTimeSeries/interfaces.ts
  frontend/src/modules/SimulationTimeSeries/settings/atoms/baseAtoms.ts
  frontend/src/modules/SimulationTimeSeries/settings/settings.tsx
  frontend/src/modules/SimulationTimeSeries/typesAndEnums.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/usePlotBuilder.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/PlotBuilder.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/PlotlyTraceUtils/createVectorTracesUtils.ts
  frontend/src/modules/SimulationTimeSeries/view/view.tsx
  frontend/src/modules/_shared/Figure.tsx
  frontend/src/modules/_shared/InplaceVolumetrics/PlotBuilder.tsx
Labels: enhancement

#858 Update to upload-artifact-v4
  .github/workflows/webviz.yml
Labels: bug, enhancement
