Repository equinor/webviz, pull requests merged in 2025-09, with the labels that each got.

#1090 Add childrenWrapperClassName prop to Label
  frontend/src/lib/components/Label/label.tsx
Labels: enhancement

#1102 Fix: Realization filter is ignored for Inplace volumes statistics
  backend_py/primary/primary/routers/inplace_volumes/router.py
Labels: bug

#1126 [DPF]: fix: Allow `ScopedQueryController` to handle multiple keys
  frontend/src/lib/utils/ScopedQueryController.ts
Labels: bug, enhancement

#1134 fix: invalid initial accumulated data in `VisualizationAssembler`
  frontend/src/modules/_shared/DataProviderFramework/visualization/VisualizationAssembler.ts
Labels: bug

#1116 Add encoding of realizations array for endpoint
  backend_py/primary/primary/routers/well_completions/router.py
  frontend/src/api/autogen/types.gen.ts
  frontend/src/modules/WellCompletions/settings/atoms/queryAtoms.ts
Labels: enhancement
