Repository equinor/webviz, pull requests merged in 2025-02, with the labels that each got.

#857 780 per day and per intvl summary vectors
  backend_py/primary/primary/routers/timeseries/converters.py
  backend_py/primary/primary/routers/timeseries/router.py
  backend_py/primary/primary/routers/timeseries/schemas.py
  backend_py/primary/primary/services/summary_delta_vectors.py
  backend_py/primary/primary/services/summary_derived_vectors.py
  backend_py/primary/primary/services/utils/arrow_helpers.py
  backend_py/primary/tests/unit/services/test_summary_delta_vectors.py
  backend_py/primary/tests/unit/services/test_summary_derived_vectors.py
  backend_py/primary/tests/unit/services/utils/test_arrow_helpers.py
  frontend/src/api/autogen/sdk.gen.ts
  frontend/src/api/autogen/types.gen.ts
  frontend/src/modules/SimulationTimeSeries/dataGenerators.ts
  frontend/src/modules/SimulationTimeSeries/settings/atoms/derivedAtoms.ts
  frontend/src/modules/SimulationTimeSeries/settings/atoms/queryAtoms.ts
  frontend/src/modules/SimulationTimeSeries/settings/settings.tsx
  frontend/src/modules/SimulationTimeSeries/utils/ensemblesVectorListHelper.ts
  frontend/src/modules/SimulationTimeSeries/utils/vectorDescriptionUtils.ts
  frontend/src/modules/SimulationTimeSeries/view/atoms/baseAtoms.ts
  frontend/src/modules/SimulationTimeSeries/view/atoms/derivedAtoms.ts
  frontend/src/modules/SimulationTimeSeries/view/hooks/usePlotBuilder.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/PlotBuilder.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/PlotlyTraceUtils/createVectorTracesUtils.ts
  frontend/src/modules/SimulationTimeSeries/view/utils/vectorSpecificationsAndQueriesUtils.ts
  frontend/src/modules/SimulationTimeSeriesSensitivity/dataGenerators.ts
  frontend/src/modules/SimulationTimeSeriesSensitivity/settings/atoms/derivedAtoms.ts
  frontend/src/modules/SimulationTimeSeriesSensitivity/view/atoms/derivedAtoms.ts
  frontend/src/modules/SimulationTimeSeriesSensitivity/view/hooks/useTimeSeriesChartTracesDataArrayBuilder.ts
  frontend/src/modules/SimulationTimeSeriesSensitivity/view/utils/createTracesUtils.ts
  frontend/src/modules/_shared/reservoirSimulationStringUtils.ts
  frontend/tests/unit/reservoirSimulationStringUtils.test.ts
Labels: enhancement

#865 fix: Wrong references in `Input` element
  frontend/src/lib/components/Input/input.tsx
Labels: bug

#872 729 allow unequal identifiers inplace volumetrics
  backend_py/primary/primary/services/inplace_volumetrics_assembler/inplace_volumetrics_assembler.py
  backend_py/primary/primary/services/sumo_access/inplace_volumetrics_types.py
  frontend/src/framework/WorkbenchServices.ts
  frontend/src/framework/types/inplaceVolumetricsFilterSettings.ts
  frontend/src/lib/components/ErrorWrapper/errorWrapper.tsx
  frontend/src/lib/components/ErrorWrapper/index.ts
  frontend/src/lib/utils/fixupUserSelection.ts
  frontend/src/modules/InplaceVolumetricsPlot/interfaces.ts
  frontend/src/modules/InplaceVolumetricsPlot/settings/atoms/baseAtoms.ts
  frontend/src/modules/InplaceVolumetricsPlot/settings/atoms/derivedAtoms.ts
  frontend/src/modules/InplaceVolumetricsPlot/settings/settings.tsx
  frontend/src/modules/InplaceVolumetricsPlot/settings/utils/plotDimensionUtils.ts
  frontend/src/modules/InplaceVolumetricsPlot/typesAndEnums.ts
  frontend/src/modules/InplaceVolumetricsPlot/view/atoms/baseAtoms.ts
  frontend/src/modules/InplaceVolumetricsPlot/view/atoms/derivedAtoms.ts
  frontend/src/modules/InplaceVolumetricsPlot/view/atoms/interfaceEffects.ts
  frontend/src/modules/InplaceVolumetricsPlot/view/atoms/queryAtoms.ts
  frontend/src/modules/InplaceVolumetricsPlot/view/view.tsx
  frontend/src/modules/InplaceVolumetricsTable/interfaces.ts
  frontend/src/modules/InplaceVolumetricsTable/settings/atoms/baseAtoms.ts
  frontend/src/modules/InplaceVolumetricsTable/settings/atoms/derivedAtoms.ts
  frontend/src/modules/InplaceVolumetricsTable/settings/settings.tsx
  frontend/src/modules/InplaceVolumetricsTable/types.ts
  frontend/src/modules/InplaceVolumetricsTable/view/atoms/baseAtoms.ts
  frontend/src/modules/InplaceVolumetricsTable/view/atoms/derivedAtoms.ts
  frontend/src/modules/InplaceVolumetricsTable/view/atoms/interfaceEffects.ts
  frontend/src/modules/InplaceVolumetricsTable/view/atoms/queryAtoms.ts
  frontend/src/modules/InplaceVolumetricsTable/view/view.tsx
  frontend/src/modules/_shared/InplaceVolumetrics/TableDefinitionsAccessor.ts
  frontend/src/modules/_shared/InplaceVolumetrics/fixupUserSelectedIdentifierValues.ts
  frontend/src/modules/_shared/components/InplaceVolumetricsFilterComponent/inplaceVolumetricsFilterComponent.tsx
Labels: enhancement

#867 Adjusted use of `BaseComponent` and always forwarding `ref` to it
  .vscode/launch.json
  frontend/src/framework/components/RealizationPicker/realizationPicker.tsx
  frontend/src/lib/components/BaseComponent/baseComponent.tsx
  frontend/src/lib/components/Button/button.tsx
  frontend/src/lib/components/Checkbox/checkbox.tsx
  frontend/src/lib/components/CollapsibleGroup/collapsibleGroup.tsx
  frontend/src/lib/components/Dropdown/dropdown.tsx
  frontend/src/lib/components/HoldPressedIntervalCallbackButton/holdPressedIntervalCallbackButton.tsx
  frontend/src/lib/components/Input/input.tsx
  frontend/src/lib/components/RadioGroup/index.ts
  frontend/src/lib/components/RadioGroup/radioGroup.tsx
  frontend/src/lib/components/Select/select.tsx
  frontend/src/lib/components/Slider/slider.tsx
  frontend/src/lib/components/Switch/switch.tsx
  frontend/src/lib/components/Table/table.tsx
  frontend/src/lib/components/TableSelect/tableSelect.tsx
  frontend/src/lib/components/TagPicker/tagPicker.tsx
  frontend/src/lib/components/ToggleButton/toggleButton.tsx
  frontend/tests/ct/select.test.tsx
Labels: enhancement, refactoring

#875 Make use of Literal in back-end schema for vfp type
  backend_py/primary/primary/routers/vfp/schemas.py
  frontend/src/api/autogen/types.gen.ts
  frontend/src/modules/Vfp/utils/vfpDataAccessor.ts
  frontend/src/modules/Vfp/utils/vfpTableClassifier.ts
Labels: enhancement

#873 Replace ValueError with service_exceptions in service layer
  backend_py/primary/primary/routers/inplace_volumetrics/converters.py
  backend_py/primary/primary/routers/seismic/router.py
  backend_py/primary/primary/services/flow_network_assembler/_group_tree_dataframe_model.py
  backend_py/primary/primary/services/flow_network_assembler/_utils.py
  backend_py/primary/primary/services/flow_network_assembler/flow_network_assembler.py
  backend_py/primary/primary/services/inplace_volumetrics_assembler/_utils.py
  backend_py/primary/primary/services/inplace_volumetrics_assembler/inplace_volumetrics_assembler.py
  backend_py/primary/primary/services/sumo_access/group_tree_access.py
  backend_py/primary/primary/services/sumo_access/observation_access.py
  backend_py/primary/primary/services/sumo_access/parameter_access.py
  backend_py/primary/primary/services/sumo_access/queries/grid3d.py
  backend_py/primary/primary/services/sumo_access/seismic_access.py
  backend_py/primary/primary/services/sumo_access/table_access.py
  backend_py/primary/primary/services/sumo_access/well_completions_access.py
  backend_py/primary/primary/services/vds_access/vds_access.py
  backend_py/primary/tests/unit/inplace_volumetrics_assembler/test_create_row_filtered_volumetric_df.py
  backend_py/primary/tests/unit/inplace_volumetrics_assembler/utils/test_create_grouped_statistical_result_table_data_polars.py
  backend_py/primary/tests/unit/inplace_volumetrics_assembler/utils/test_create_per_group_summed_realization_volume_df.py
  backend_py/primary/tests/unit/inplace_volumetrics_assembler/utils/test_inplace_volumetrics_utils.py
Labels: enhancement

#878 Adjust slider component
  frontend/src/lib/components/Slider/slider.tsx
Labels: bug, enhancement

#882 Fix related to pylint required change to names of axes
  backend_py/primary/primary/services/vds_access/vds_access.py
Labels: bug
